export const Questions = [
  {
    prompt: "What is the capital of France?",
    optionA: "London",
    optionB: "Berlin",
    optionC: "Paris",
    optionD: "Rome",
    answer: "optionC",
  },
  {
    prompt: "8 x 5 equals:",
    optionA: "32",
    optionB: "40",
    optionC: "24",
    optionD: "16",
    answer: "optionB",
  },
  {
    prompt: "Which planet is closest to the sun?",
    optionA: "Mars",
    optionB: "Earth",
    optionC: "Mercury",
    optionD: "Venus",
    answer: "optionC",
  },
  {
    prompt: "What is the largest ocean on Earth?",
    optionA: "Atlantic Ocean",
    optionB: "Pacific Ocean",
    optionC: "Indian Ocean",
    optionD: "Arctic Ocean",
    answer: "optionB",
  },
  {
    prompt: "Complete the proverb: 'Early to bed, early to...'",
    optionA: "work",
    optionB: "play",
    optionC: "rise",
    optionD: "sleep",
    answer: "optionC",
  },
  {
    prompt: "What is the chemical symbol for water?",
    optionA: "CO2",
    optionB: "H2O",
    optionC: "NaCl",
    optionD: "NH3",
    answer: "optionB",
  },
  {
    prompt: "How many sides does a hexagon have?",
    optionA: "4",
    optionB: "5",
    optionC: "6",
    optionD: "8",
    answer: "optionC",
  },
  {
    prompt: "What is the square root of 16?",
    optionA: "2",
    optionB: "3",
    optionC: "4",
    optionD: "5",
    answer: "optionC",
  },
  {
    prompt: "In which year did World War II begin?",
    optionA: "1914",
    optionB: "1939",
    optionC: "1945",
    optionD: "1950",
    answer: "optionB",
  },
  {
    prompt: "What is the name of the tallest mountain in the world?",
    optionA: "Mount Everest",
    optionB: "K2",
    optionC: "Kangchenjunga",
    optionD: "Lhotse",
    answer: "optionA",
  },
];
